# https://taskfile.dev

version: "3"

vars:
  ANDROID_API: "21"
env:
  GOOS: "android"


tasks:
  build:
    vars:
      ARCH: "arm64"
    env:
      GOARCH: '{{.ARCH}}'
      CGO_ENABLED: "0"
    cmds:
      - go build -o zapret_{{.ARCH}}

  cgo_build_arm64:
    env:
      GOARCH: "arm64"
      CGO_ENABLED: "1"
      CC: 'aarch64-linux-android{{.ANDROID_API}}-clang'
      CXX: 'aarch64-linux-android{{.ANDROID_API}}-clang++'
    cmds:
      - go build -o zapret_arm64

  cgo_build_arm:
    env:
      GOARCH: "arm"
      CGO_ENABLED: "1"
      CC: 'armv7a-linux-androideabi{{.ANDROID_API}}-clang'
      CXX: 'armv7a-linux-androideabi{{.ANDROID_API}}-clang++'
    cmds:
      - go build -o zapret_arm

  cgo_build_x64:
    env:
      GOARCH: "amd64"
      CGO_ENABLED: "1"
      CC: 'x86_64-linux-android{{.ANDROID_API}}-clang'
      CXX: 'x86_64-linux-android{{.ANDROID_API}}-clang++'
    cmds:
      - go build -o zapret_x64
  
  cgo_build_x86:
    env:
      GOARCH: "386"
      CGO_ENABLED: "1"
      CC: 'i686-linux-android{{.ANDROID_API}}-clang'
      CXX: 'i686-linux-android{{.ANDROID_API}}-clang++'
    cmds:
      - go build -o zapret_x86