# https://taskfile.dev

version: "3"

vars:
  ANDROID_API: "21"
  CGO: "1"
env:
  GOOS: "android"

tasks:
  build:
    deps:
      - build_arm64
      - build_arm
      - build_x64
      - build_x86
      
  build_arm64:
    env:
      GOARCH: "arm64"
      CGO_ENABLED: '{{.CGO}}'
      CC: "aarch64-linux-android{{.ANDROID_API}}-clang"
      CXX: "aarch64-linux-android{{.ANDROID_API}}-clang++"
    cmds:
      - go build -o build/zapret_arm64

  build_arm:
    env:
      GOARCH: "arm"
      CGO_ENABLED: '{{.CGO}}'
      CC: "armv7a-linux-androideabi{{.ANDROID_API}}-clang"
      CXX: "armv7a-linux-androideabi{{.ANDROID_API}}-clang++"
    cmds:
      - go build -o build/zapret_arm

  build_x64:
    env:
      GOARCH: "amd64"
      CGO_ENABLED: '{{.CGO}}'
      CC: "x86_64-linux-android{{.ANDROID_API}}-clang"
      CXX: "x86_64-linux-android{{.ANDROID_API}}-clang++"
    cmds:
      - go build -o build/zapret_x64

  build_x86:
    env:
      GOARCH: "386"
      CGO_ENABLED: '{{.CGO}}'
      CC: "i686-linux-android{{.ANDROID_API}}-clang"
      CXX: "i686-linux-android{{.ANDROID_API}}-clang++"
    cmds:
      - go build -o build/zapret_x86
